### ISSUE TITLE
[Setting] CI CD를 위한 github workflow 작성 및 docker file 작성

### ISSUE THREAD

**Issue by RudyLuvIt** [TEAM-ALOM/dorundorun-Be#3]
# 🧗 기능 개요
CI CD를 위한 github action workflow 파일을 작성하고 docker hub push, pull을 위한 docker file을 작성합니다
### ✅ To-do
- [x] Docker File 작성
- [ ] Workflow File 작성
- [ ] 전체 기능 테스트
