### ISSUE TITLE
[Test] 업적 테스트

### ISSUE THREAD

**Issue by KyunghoYeom** [TEAM-ALOM/dorundorun-Be#34]
# 🧗 기능 개요
업적 테스트 구현
### ✅ To-do
- [ ] reward, assign 로직 등 정상 동작 여부 확인
- [ ] 새로 적용된 global exception 적용
- [ ] background 대소문자 상관없이 허용하는 테스트 코드 추가
