### ISSUE TITLE
[Feat] 러닝 기록 아이템 정보 추가

### ISSUE THREAD

**Issue by Yooonjeong** [TEAM-ALOM/dorundorun-Be#39]
# 🧗 기능 개요
러닝 시점의 아이템 정보를 러닝 기록에 추가합니다.

### ✅ To-do
- [x] 러닝 엔티티 필드 추가
- [x] 러닝 기록 service 수정
- [x] 러닝 기록 테스트 코드 수정

### 📝 기타
