### ISSUE TITLE
[Feat] 상점 구현

### ISSUE THREAD

**Issue by xaxeon** [TEAM-ALOM/dorundorun-Be#5]
# 🧗 기능 개요
상점 구현

### ✅ To-do
- [x] 소유 여부에 따라 정렬해 조회
- [ ] 새 아이템 추가/삭제
- [x] 아이템 구매
- [x] 소유한 아이템 착용/해제
